- name: install Redis server
  apt:
     name: redis-server
     state: present
     update_cache: yes

- name: update Redis config file from local address to 0.0.0.0
  replace:
       path: /etc/redis/redis.config
       regexp: '127.0.0.1'
       replace: '0.0.0.0'


- name: start redis
  systemd:
     name: redis
    state: restarted
    enabled: yes
