- name: Demo on loop
  hosts: all
  tasks:
    - name: Print fruitnames
      debug:
        msg: "Fruit = {{ item.name }}"
      loop:
        - name: banana
        -name: apple
        -name: orange
      loop_control:
        label: "{{ item.name }}"  