- name: Demo on loop
  hosts: all
  tasks:
    - name: Print fruitnames
      debug:
        msg: "Fruit = {{ item.name }}"
      loop:
        - name: banana
          color: yellow
        -name: apple
         color: red
        -name: orange
        color: oran
      loop_control:
        label: "{{ item.name }}"  