- name: Demo on loop
  hosts: all
  tasks:
    - name: Print fruitnames
      debug:
        msg: "Fruit = {{ item }}"
      loop:
       - orange
        - apple
        - redmilk

    - name: Loop variable
      debug:
        msg: "{{ myvar }}"
      loop:
        - apple
        - banana
        - pear
      loop_control:
        loop_var: myvar