- name: Setup roboshop project
  hosts: all
  become: yes
  
  roles:
    - role: redis
      tags: redis
      when: COMPONENT == "redis"

    - role: users
      tags: users
      when: COMPONENT == "users"

    - role: login
      tags: login
      when: COMPONENT == "login"

     