- name: Setup todo project
  hosts: all
  become: yes
  
  roles:
    - role: redis
      tags: redis
      when: COMPONENT == "redis"


    - role: users
      tags: users
      when: COMPONENT == "users"

    
     