- name: Setup todo project
  hosts: all
  become: yes
  become_user: root
  
  roles:
    - role: redis
      tags: redis
      when: COMPONENT == "redis"


    - role: users
      tags: users
      when: COMPONENT == "users"

    - role: login
      tags: login
      when: COMPONENT == "login"
    
     