- name: Copy {{COMPONENT}} Service file
  copy:
    src: "{{COMPONENT}}.service"
    dest: /etc/systemd/system/{{COMPONENT}}.service
    remote_src: yes
    owner: ubuntu
    group: ubuntu


- name: Start {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    daemon_reload: yes
    state: started
    enabled: yes