- name: Copy systemd Service file
  template:
    src: "login.service".yml
    dest: /etc/systemd/system/login.service
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    

- name: Start login Service
  systemd:
    name: "login"
    daemon_reload: yes
    state: started
    enabled: yes